<a href="https://colab.research.google.com/github/cse240840131002-ship-it/GTU_Internship/blob/main/Day_4(09_07_26).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from re import T
a=[1,2,3,4,11,13,12,10,5,6,7,8,9]
serise_a=pd.Series(a)
print(type(serise_a),"\n",serise_a.sort_values(ascending=True))

<class 'pandas.core.series.Series'>
 0      1
1      2
2      3
3      4
8      5
9      6
10     7
11     8
12     9
7     10
4     11
6     12
5     13
dtype: int64

In [ ]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
energy_df=pd.DataFrame(data=data)
print(energy_df)

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [ ]:
energy_df.isnull().sum()

Energy Source               0
Energy Consumption (MWh)    2
Cost (Million $)            2
dtype: int64

In [ ]:
# Remove rows with any missing values

cleaned_df = energy_df.dropna()

subset_df  = energy_df.dropna(subset = "Energy Consumption (MWh)")
print("\nData After Removing Rows with Missing Values:")
print(cleaned_df)

print(subset_df)

print(energy_df)

Data After Removing Rows with Missing Values:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
2    Hydropower                    2900.0               NaN
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [ ]:
# Impute missing values in 'Energy Consumption (MWh)' with the mean

energy_df.iloc[:, 1] = energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean())

# Impute missing values in 'Cost (Million $)' with the mean

energy_df.iloc[:, 2] = energy_df["Cost (Million $)"].fillna(energy_df["Cost (Million $)"].mean())

print("\nData After Imputing Missing Values with Mean:")

print(energy_df)

Data After Imputing Missing Values with Mean:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [ ]:

forward_filled_df = energy_df.ffill()

# energy_df = energy_df.ffill()

print("before forward filling")

print(energy_df)


# print(forward_filled_df.columns)

print("\nData After Forward Filling:")

print(forward_filled_df)

before forward filling
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Data After Forward Filling:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [ ]:
energy_df1 = energy_df.copy()
energy_df1

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [ ]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

energy_df = pd.DataFrame(data)

# Create copies
energy_df_mean = energy_df.copy()
energy_df_ffill = energy_df.copy()
energy_df_bfill = energy_df.copy()

# ---------------- Mean Imputation ----------------
energy_df_mean["Energy Consumption (MWh)"] = energy_df_mean["Energy Consumption (MWh)"].fillna(
    energy_df_mean["Energy Consumption (MWh)"].mean()
)

energy_df_mean["Cost (Million $)"] = energy_df_mean["Cost (Million $)"].fillna(
    energy_df_mean["Cost (Million $)"].mean()
)

print("Data After Mean Imputation:")
print(energy_df_mean)

# ---------------- Forward Fill ----------------
print("\nBefore Forward Fill:")
print(energy_df_ffill)

forward_filled_df = energy_df_ffill.ffill()

print("\nData After Forward Fill:")
print(forward_filled_df)

# ---------------- Backward Fill ----------------
print("\nBefore Backward Fill:")
print(energy_df_bfill)

backward_filled_df = energy_df_bfill.bfill()

print("\nData After Backward Fill:")
print(backward_filled_df)

Original DataFrame
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

After Forward Fill
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    1200.0             400.0
2    Hydropower                    2900.0             400.0
3    Geothermal                    2900.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [ ]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

energy_df = pd.DataFrame(data)

# Create copies
energy_df_mean = energy_df.copy()
energy_df_ffill = energy_df.copy()
energy_df_bfill = energy_df.copy()

# ---------------- Mean Imputation ----------------
energy_df_mean["Energy Consumption (MWh)"] = energy_df_mean["Energy Consumption (MWh)"].fillna(
    energy_df_mean["Energy Consumption (MWh)"].mean()
)

energy_df_mean["Cost (Million $)"] = energy_df_mean["Cost (Million $)"].fillna(
    energy_df_mean["Cost (Million $)"].mean()
)

print("Data After Mean Imputation:")
print(energy_df_mean)

# ---------------- Forward Fill ----------------
print("\nBefore Forward Fill:")
print(energy_df_ffill)

forward_filled_df = energy_df_ffill.ffill()

print("\nData After Forward Fill:")
print(forward_filled_df)

# ---------------- Backward Fill ----------------
print("\nBefore Backward Fill:")
print(energy_df_bfill)

backward_filled_df = energy_df_bfill.bfill()

print("\nData After Backward Fill:")
print(backward_filled_df)

Data After Mean Imputation:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Before Forward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Data After Forward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    1200.0             400.0
2    Hydropower                    2900.0             400.0
3    Geothermal                    2900.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Before Backward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Data After Backward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2900.0             400.0
2    Hydropower                    2900.0             150.0
3    Geothermal                    2500.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [1]:
#ToDay Task
import pandas as pd
import numpy as np

In [3]:
# Import Dataset

df = pd.read_csv("/content/renewable_energy.csv")

print("Original Dataset\n")
print(df.to_string(index=True))

Original Dataset

  Energy Source  Energy Consumption (MWh)  Cost (Million $)  CO2 Reduction (Tons)  Country
0         Solar                    1200.0             200.0                 500.0    India
1          Wind                    2450.0             400.0                 900.0  Germany
2    Hydropower                    2900.0             250.0                1200.0   Canada
3    Geothermal                       NaN             150.0                 700.0  Iceland
4       Biomass                    2500.0               NaN                 800.0   Brazil
5         Solar                    3100.0             500.0                   NaN    India
6          Wind                    2800.0             450.0                1000.0      USA
7    Hydropower                       NaN             300.0                1100.0   Canada
8       Biomass                    2200.0             210.0                 750.0    India
9    Geothermal                    1800.0             180.0                 650.0    Kenya

In [ ]:
# Relationship Between Columns
# -----------------------------------------------------

# Energy Consumption ↔ CO2 Reduction
# Positive relationship.
# More renewable energy generally reduces more CO2.

# Energy Consumption ↔ Cost
# Moderate positive relationship.
# Large projects generally cost more.

# Energy Source ↔ Cost
# Different technologies have different installation costs.

# Country ↔ Energy Source
# Certain countries prefer specific renewable resources.

# Country ↔ CO2 Reduction
# Depends on renewable energy adoption.

In [5]:
# Check Null Values
# -----------------------------------------------------

print("\nNull Values")
print(df.isnull().sum())

Null Values
Energy Source               0
Energy Consumption (MWh)    2
Cost (Million $)            1
CO2 Reduction (Tons)        1
Country                     0
dtype: int64

In [11]:

# Forward Fill
df_forward = df.ffill()

print("\n========== Dataset After Forward Fill ==========")
print(df_forward)

# Backward Fill
df_backward = df.bfill()

print("\n========== Dataset After Backward Fill ==========")
print(df_backward)

========== Dataset After Forward Fill ==========
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                   1200.00        200.000000
1          Wind                   2450.00        400.000000
2    Hydropower                   2900.00        250.000000
3    Geothermal                   2368.75        150.000000
4       Biomass                   2500.00        293.333333
5         Solar                   3100.00        500.000000
6          Wind                   2800.00        450.000000
7    Hydropower                   2368.75        300.000000
8       Biomass                   2200.00        210.000000
9    Geothermal                   1800.00        180.000000

   CO2 Reduction (Tons)  Country
0            500.000000    India
1            900.000000  Germany
2           1200.000000   Canada
3            700.000000  Iceland
4            800.000000   Brazil
5            844.444444    India
6           1000.000000      USA
7           1100.000000   Canada
8            750.000000    India
9            650.000000    Kenya

========== Dataset After Backward Fill ==========
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                   1200.00        200.000000
1          Wind                   2450.00        400.000000
2    Hydropower                   2900.00        250.000000
3    Geothermal                   2368.75        150.000000
4       Biomass                   2500.00        293.333333
5         Solar                   3100.00        500.000000
6          Wind                   2800.00        450.000000
7    Hydropower                   2368.75        300.000000
8       Biomass                   2200.00        210.000000
9    Geothermal                   1800.00        180.000000

   CO2 Reduction (Tons)  Country
0            500.000000    India
1            900.000000  Germany
2           1200.000000   Canada
3            700.000000  Iceland
4            800.000000   Brazil
5            844.444444    India
6           1000.000000      USA
7           1100.000000   Canada
8            750.000000    India
9            650.000000    Kenya

In [6]:
# Handle Missing Values
# -----------------------------------------------------
# Numerical columns -> Replace with Mean

print("\nDataset Before Handling Null Values")
print(df)
df["Energy Consumption (MWh)"] = df["Energy Consumption (MWh)"].fillna(
    df["Energy Consumption (MWh)"].mean()
)

df["Cost (Million $)"] = df["Cost (Million $)"].fillna(
    df["Cost (Million $)"].mean()
)

df["CO2 Reduction (Tons)"] = df["CO2 Reduction (Tons)"].fillna(
    df["CO2 Reduction (Tons)"].mean()
)

print("\nDataset After Handling Null Values")
print(df)

Dataset Before Handling Null Values
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0               NaN
5         Solar                    3100.0             500.0
6          Wind                    2800.0             450.0
7    Hydropower                       NaN             300.0
8       Biomass                    2200.0             210.0
9    Geothermal                    1800.0             180.0

   CO2 Reduction (Tons)  Country
0                 500.0    India
1                 900.0  Germany
2                1200.0   Canada
3                 700.0  Iceland
4                 800.0   Brazil
5                   NaN    India
6                1000.0      USA
7                1100.0   Canada
8                 750.0    India
9                 650.0    Kenya

Dataset After Handling Null Values
  Energy Source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                   1200.00        200.000000
1          Wind                   2450.00        400.000000
2    Hydropower                   2900.00        250.000000
3    Geothermal                   2368.75        150.000000
4       Biomass                   2500.00        293.333333
5         Solar                   3100.00        500.000000
6          Wind                   2800.00        450.000000
7    Hydropower                   2368.75        300.000000
8       Biomass                   2200.00        210.000000
9    Geothermal                   1800.00        180.000000

   CO2 Reduction (Tons)  Country
0            500.000000    India
1            900.000000  Germany
2           1200.000000   Canada
3            700.000000  Iceland
4            800.000000   Brazil
5            844.444444    India
6           1000.000000      USA
7           1100.000000   Canada
8            750.000000    India
9            650.000000    Kenya

In [8]:
# Analysis
# -----------------------------------------------------

print("\n<--Average Energy Consumption-->")
print(df["Energy Consumption (MWh)"].mean())

print("\nAverage Cost")
print(df["Cost (Million $)"].mean())

print("\n<--Average CO2 Reduction-->")
print(df["CO2 Reduction (Tons)"].mean())

print("\nEnergy Source Frequency")
print(df["Energy Source"].value_counts())

print("\nCountry Frequency")
print(df["Country"].value_counts())

<--Average Energy Consumption-->
2368.75

Average Cost
293.3333333333333

<--Average CO2 Reduction-->
844.4444444444446

Energy Source Frequency
Energy Source
Solar         2
Wind          2
Hydropower    2
Geothermal    2
Biomass       2
Name: count, dtype: int64

Country Frequency
Country
India      3
Canada     2
Germany    1
Iceland    1
Brazil     1
USA        1
Kenya      1
Name: count, dtype: int64

In [9]:
# Correlation
# -----------------------------------------------------

print("\nCorrelation Matrix")
print(df.select_dtypes(include=np.number).corr())

Correlation Matrix
                          Energy Consumption (MWh)  Cost (Million $)  \
Energy Consumption (MWh)                  1.000000          0.657155
Cost (Million $)                          0.657155          1.000000
CO2 Reduction (Tons)                      0.741336          0.432472

                          CO2 Reduction (Tons)
Energy Consumption (MWh)              0.741336
Cost (Million $)                      0.432472
CO2 Reduction (Tons)                  1.000000

In [10]:
print("\n================ SUMMARY ================")

print("""
1. Imported a renewable energy dataset using Pandas.
2. Explored the dataset using info(), describe(), and value_counts().
3. Identified relationships between different features.
4. Checked missing values.
5. Replaced missing numerical values using mean imputation.
6. Calculated averages and frequency distributions.
7. Generated a correlation matrix for numerical features.
8. The dataset indicates that higher renewable energy production
   generally results in greater CO2 reduction and may involve
   higher project costs.
""")

================ SUMMARY ================

1. Imported a renewable energy dataset using Pandas.
2. Explored the dataset using info(), describe(), and value_counts().
3. Identified relationships between different features.
4. Checked missing values.
5. Replaced missing numerical values using mean imputation.
6. Calculated averages and frequency distributions.
7. Generated a correlation matrix for numerical features.
8. The dataset indicates that higher renewable energy production
   generally results in greater CO2 reduction and may involve
   higher project costs.